version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-burh
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-burh
    restart: always
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres

volumes:
  postgres_data:
